strictness: medium

pylint:
  options:
    bad-names: foo,baz,toto,tutu,tata,data
    # max-args default = 5
    max-args: 15
    # max-locals default = 15
    max-locals: 50
    # max-branches default = 15
    max-branches: 15
  disable:
    - line-too-long
    - protected-access
    # remove if python2.7 support is dropped
    - useless-object-inheritance
    - old-style-class

pyflakes:
  disable:
    - F401
    - F841
    # let pylint used-before-assignment handle this
    - F821

pep8:
  options:
    max-line-length: 120
  disable:
    - E501
    - E241

mccabe:
  options:
    # max-complexity default = 10
    max-complexity: 22

pyroma:
  run: true

pep257:
  run: false