inherits:
  - strictness_medium
  
pylint:
  options:
    max-args: 7
  disable:
    - line-too-long
    - protected-access
    - unused-import
    - unused-variable
    - unused-argument
    - unused-wildcard-import

pyflakes:
  disable:
    - F401
    - F841
    # let pylint used-before-assignment handle this
    - F821

pep8:
  options:
    max-line-length: 88
  disable:
    - E501
    - E241

pyroma:
  run: false

pep257:
  run: false